name: Sync Version

on:
  push:
    branches: [ master ]
    paths:
      - 'composer.json'
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Update VERSION file
      run: php .github/scripts/update-version.php

#    - name: Commit VERSION file
#      uses: stefanzweifel/git-auto-commit-action@v4
#      with:
#        commit_message: "chore: Update VERSION file to match composer.json"
#        file_pattern: VERSION
#        branch: master